name: Deploy to EC2

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Run Build (if exists)
        run: npm run build --if-present

      - name: Start App Health Check
        run: |
          node index.js &
          sleep 5
          pgrep node

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/ci-cd-project
            git fetch origin
            git reset --hard origin/main
            npm install
            pm2 restart sampleci